@startuml
actor User as user

participant "Server" as server
participant "Users" as users
participant "Profile" as profile
participant "Role_User" as role_user
participant "Role" as role
participant "Refresh_Token" as refresh_token
participant "login_history" as login_history

user -> server: POST /auth/register (email, password, first_name, last_name)

server -> server: validateInput(email, password, first_name, last_name)
alt Input Not Valid
    server --> user: 400 Bad Request
else Input Valid

    server -> users: findByEmail(email)
    alt Email Already Exists
        users --> server: user
        server --> user: 409 Conflict\nEmail already exists
    else Email Unique

        server -> server: hashPassword(password)

        server -> users: create(email, password_hash, status:"active")
        users --> server: new_user(id)

        server -> role: findByName("Customer")
        role --> server: role(id)

        server -> role_user: create(user_id, role_id)
        role_user --> server: Done

        server -> profile: create(user_id, first_name, last_name)
        profile --> server: Done

        server -> server: generateTokens(user + ["Customer"])

        server -> refresh_token: insert(user_id, argon2_hash, expires_at)
        refresh_token --> server: Done

        server -> login_history: insert(user_id, ip, device)
        login_history --> server: Done

        server -> user: 201 Created + tokens
    end
end
@enduml
